### DISCUSSION TITLE
WXT Store Upload/Submit

### DISCUSSION THREAD

**Discussion by mrshappy0** [wxt-dev/wxt#1545] [Q&A] [answered]
I've read through the [docs](https://wxt.dev/guide/essentials/publishing#automation) for automating the publishing process of extensions. 

I am using something like this:
```
            - name: Submit to Chrome Store
              run: |
                  pnpm wxt submit \
                    --chrome-zip .output/*-chrome.zip \
              env:
                  CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
                  CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
                  CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
                  CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
```

I'm wondering if I'm missing something but does a `wxt upload` cmd exist? `wxt submit` uploads AND submits for review. I'd rather upload and be able to update Chrome Web Store assets and info then manually submit for review.

**Comment by aklinker1** [comment, marked as answer]
Haha yup, you're missing something, but it's my fault - I don't link to the docs for all the options in the store docs.

If you run the `wxt submit init` or [`wxt submit --help`](https://wxt.dev/api/cli/wxt-submit.html), these commands would have shown you all the options, including the `--chrome-skip-submit-review` flag/`CHROME_SKIP_SUBMIT_REVIEW` env var.

```yaml
env:
  CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
  CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
  CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
  CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
  CHROME_SKIP_SUBMIT_REVIEW: true
```

I'll update the docs with a link to all the options, because its just missing 🤦
