### ISSUE TITLE
Investigate ways of generating `_locales` based on translation files

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#217]
> No, I meant... For someone who's not using `vue-i18n` and only relies on `browser.i18n` he'd be defining a mess in `public/_locales` because the syntax is too verbose. 
> 
> But if someone wanted to use `vue-i18n` they'd be defining only extension name and description within the context of `browser.i18n` and the rest can all live inside `vue-i18n` locale dir.
> 
> Am I right? If not, I'd be trying to figure out the way to use only vue-i18n and somehow at the build-time generate locales needed for parts that `browser.i18n` can access, such as `manifest.json` file property values.

_Originally posted by @dvlden in https://github.com/wxt-dev/wxt/issues/187#issuecomment-1799136362_
            
> @dvlden Yes, that is an option, that could be a simple Vite plugin. I need to research other patterns before committing to adding that logic to WXT directly. I don't want to add something that only works for one framework's one library.

_Originally posted by @aklinker1  in https://github.com/wxt-dev/wxt/issues/187#issuecomment-1799301604_

Goal here is to provide some kind of vite plugin or config option to generate the `_locales` directory from another localization file. This would also need to integrate with the type augmentation for `browser.runtime.getMessage`.

You shouldn't have to manage translation files in multiple directories.

**Comment by aklinker1** [comment]
Interesting tool, I hadn't heard about it before. I don't think it is the solution to combining manifest translations and other translation files though...

https://github.com/lokalise/i18n-ally/wiki/Custom-Framework seems relevant, at least for adding editor support.

**Comment by mefengl** [comment]
Yes, supporting this tool will greatly simplify the checking and editing of i18n files (it likely already support Chrome i18n and vue-i18n).

---

Also, I have reviewed the `i18n` and `vue-i18n` wxt-examples and have gained a basic understanding of the situation. The current official structure, as per Google Chrome's standards, is:

```
public/_locales/en/messages.json
public/_locales/ko/messages.json
```

For vue-i18n, WXT needs an official solution for the manifest, and a *.json solution for other files:

```
assets/locales/en.json
assets/locales/ko.json
```

The objective is to utilize `assets/locales/*.json` for all i18n tasks (including manifest) across all frameworks, aiming to make this a built-in feature for WXT, possibly supporting the Google Chrome official solution simultaneously.

Additionally, WXT requires a feature similar to `useI18n` to ensure type safety by verifying message keys exist.

Is my understanding correct?

**Comment by aklinker1** [comment]
Correct, but it also needs to support react, Svelte, and any other i18n libraries.

This is why I mentioned a custom vite plugin rather than something built into WXT - supporting every i18n library in core would not be a good approach.

**Comment by mefengl** [comment]
If type safety is not a concern, then actually, a plugin might not be necessary. 
Because the process of converting from `assets/locales/<lang>.json` to `public/_locales/<lang>/messages.json` is independent of the framework.

**Comment by aklinker1** [comment]
True, but features like placeholders, re-using strings, and pluralization are different between most libraries.

So just reading JSON from one place won't always work.

**Comment by mefengl** [comment]
> You shouldn't have to manage translation files in multiple directories.


Initially, it was a bit confusing because I thought solving the problem mentioned above merely required a pure JavaScript implementation that should be independent of any framework, as it only needs to move the file.

With the i18next example, I now understand what you mean:

```
i18next.init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        itemCount: "{{count}} item",
        itemCount_plural: "{{count}} items"
      }
    }
  }
});

i18next.t('itemCount', { count: 1 }); // 1 item
i18next.t('itemCount', { count: 5 }); // 5 items
```

In this case, it does require a framework-specific approach.

**Comment by dvlden** [comment]
At the moment, I am opting out entirely of Vue i18n and using browser built-in i18n for all translation messages. 

It is disaster to maintain, but I wouldn't want to use i18n dependency inside of injection script or background / worker.

**Comment by mefengl** [comment]
@dvlden

I've really given `i18n-ally` a try in my project and figured out how to configure it.

First, install [i18n-ally](https://marketplace.visualstudio.com/items?itemName=lokalise.i18n-ally).

Then, add the following to your `.vscode/settings.json`:

```
  "i18n-ally.enabledFrameworks": [
    "chrome-ext"
  ],
  "i18n-ally.localesPaths": [
    "your/path/to/_locales"
  ]
```

After that, you should see something like this:

![image](https://github.com/wxt-dev/wxt/assets/71683364/5db61441-1a14-4e25-8d53-732c807601c3)

Hope this is helpful

**Comment by aklinker1** [comment]
Ok, I'm convinced that WXT can't provide a solution for all localization frameworks, but it should be able to improve the existing i18n APIs and localization files.

Here's what I propose:

1. Create a new folder called `locales/` recognized by WXT
2. Place any files with translations directly in it (support YAML, JSON 5, and regular JSON)
3. Improve the format of the localization files themselves (nested keys, optionally use a simple string instead of an object with a message, etc)

I'll share a complete example of what I'm thinking in a bit.

**Comment by aklinker1** [comment]
For example, my [GitHub Better Line Counts](https://github.com/aklinker1/github-better-line-counts) extension. It's not localized, but if I were to localize it, it would look something like this:

```
src/
  locales/
    en.yml
    ...
```

```yml
# src/locales/en.yml
name: GitHub Better Line Counts
description: Remove generated files from GitHub line counts
diffs:
  additionsText:
    1: $count$ addition
    n: $count$ additions
  deletionsText: 
    1: $count$ deletion
    n: $count$ deletions
  generatedText: 
    1: $count$ generated line.
    n: $count$ generated lines.
  additionsSymbol: +$count$
  deletionsSymbol: −$count$
  generatedSymbol: ⌁$count$
options:
  privateRepos:
    title: Access Private Repos
    description1: "Optional:"
    description2: To recalculate the diff on private repos, the extension needs a GitHub PAT to authenticate API requests.
    description3: Click here
    description4: to create one.
    invalidToken: Token is invalid
    validToken: Token is valid
    checking: Checking token...
    username: "Username: {username}"
  enabled:
    title: Show Generated Line Counts
    description1: Along with
    description2: +additions
    description3: and
    description4: −deletions
    description5: ", show a third number for"
    description6: ⌁generated
    description7: lines.
  customLists:
    title: Custom Lists
    description1: Use
    description1: minimatch
    description1: glob patterns to mark files as generated accross all repos.
    allRepos: All Repos
    customRepoPlaceholder: |
      Enter glob patterns:
      *.lock
      **/vendor/**
```

Some comments:

1. You don't need to use the `{ message: ..., description?: ..., placeholders?: ... }` form the Chrome extensions require. If you just set a string value for a key, WXT will convert to it the form chrome extensions expect. You can still use the longer form if you want.
2. Chrome doesn't have a built-in solution for pluralization. [They recommend](https://www.chromium.org/developers/design-documents/extensions/how-the-extension-system-works/i18n/#plural-form) using "plural neutral forms" (`Additions: $count$` instead of `$count$ additions`), which IMO doesn't always work. I plan on supporting plural forms, see `diffs.*Text` for an example.
